### ISSUE TITLE
Write a python gdeploy wrapper

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/python-gdeploy#1]
A python gdeploy wrapper has to be written, so that all the tasks that are possible by gdeploy must be executable as python modules. The wrapper should generate gdeploy config files and also execute them via cli using the command `gdeploy -c <conf-file>`

**Comment by nnDarshan** [comment]
https://github.com/Tendrl/specifications/issues/49

**Comment by mbukatov** [comment]
Wouldn't be better to do these changes in gdeploy itself?
